### ISSUE TITLE
Line 748: syntax error: unexpected “fi”

### ISSUE THREAD

**Issue by npmstart-pray** [ttgapers/cakeqos-merlin#56] opened 2020-07-02 23:41 UTC
Subject says all. Someone left something dangling, or forgot to clear something away.

**Comment by Adamm00** [comment] 2020-07-03 03:06
Was this during an update?

**Comment by ttgapers** [comment] 2020-07-03 03:16
yup. I got it on an update on two routers earlier today.

**Comment by Adamm00** [comment] 2020-07-03 03:20
Then this is a duplicate of #53 and #44 which should be no longer relevant as we hard exit after updates once again. I previously tried to explain this issue but others refused to accept the logic behind it.

**Closed by Adamm00** 2020-07-03 03:20 UTC
