### ISSUE TITLE
individual extra option settings and connection profiles

### ISSUE THREAD

**Issue by RobotsAreCrazy** [ttgapers/cakeqos-merlin#47] opened 2020-06-28 12:20 UTC
TechTinkerer here hey all!

can a way to manually add extra options, individually for download\upload be added to the menu please?

also how about a preset be added for different connection types e.g docsis, pppoe-ptm etc that adds recommended extra options depending on connection chosen?

**Comment by Adamm00** [comment] 2020-06-28 13:40
Duplicate of #46

**Closed by Adamm00** 2020-06-28 13:40 UTC
